//go:build amd64 && !js

// Code generated by command: go run gen.go -out matrix_avx/add.s -stubs matrix_avx/stub.go -pkg matrix_avx. DO NOT EDIT.

#include "textflag.h"

// func VecAddAVX(a []float32, b []float32, res []float32)
// Requires: AVX
TEXT ·VecAddAVX(SB), NOSPLIT, $0-72
	MOVQ a_base+0(FP), AX
	MOVQ b_base+24(FP), CX
	MOVQ res_base+48(FP), DX
	MOVQ a_len+8(FP), BX

loop_unrolled:
	CMPQ    BX, $0x20
	JL      loop_8
	VMOVUPS (AX), Y0
	VMOVUPS 32(AX), Y1
	VMOVUPS 64(AX), Y2
	VMOVUPS 96(AX), Y3
	VMOVUPS (CX), Y4
	VMOVUPS 32(CX), Y5
	VMOVUPS 64(CX), Y6
	VMOVUPS 96(CX), Y7
	VADDPS  Y0, Y4, Y0
	VADDPS  Y1, Y5, Y1
	VADDPS  Y2, Y6, Y2
	VADDPS  Y3, Y7, Y3
	VMOVUPS Y0, (DX)
	VMOVUPS Y1, 32(DX)
	VMOVUPS Y2, 64(DX)
	VMOVUPS Y3, 96(DX)
	ADDQ    $0x80, AX
	ADDQ    $0x80, CX
	ADDQ    $0x80, DX
	SUBQ    $0x20, BX
	JMP     loop_unrolled

loop_8:
	CMPQ    BX, $0x08
	JL      done
	VMOVUPS (AX), Y0
	VMOVUPS (CX), Y1
	VADDPS  Y0, Y1, Y0
	VMOVUPS Y0, (DX)
	ADDQ    $0x20, AX
	ADDQ    $0x20, CX
	ADDQ    $0x20, DX
	SUBQ    $0x08, BX
	JMP     loop_8

done:
	RET
